#!/bin/env bash

source minimenu
source util

menu="
    1 SSH
    2 Automations
    3 Info
"

setup() {
  local row col
  stty -echo
  tput civis >&2  # make cursor invisible
  INIT_Y=$(gety) INIT_X=$(getx)
}

restore() {
  tput cnorm >&2  # make cursor appear normal
  tput rc >&2     # restore cursor position
  stty sane
  setabsyx $((INIT_Y<0?0:INIT_Y)) $((INIT_X<0?0:INIT_X))
  tput ed >&2     # erase display
}


main() {
  # r=$((RANDOM % 256))
  # g=$((RANDOM % 256))
  # b=$((RANDOM % 256))
  # setrgb $r $g $b
  # r=100
  # while true; do
  #   while (( r < 230 )); do
  #     setrgb $(( r++ )) 0 0
  #     addstr "The Drench" 1 20
  #     sleep 0.001
  #   done
  #   while (( r > 50 )); do
  #     setrgb $(( --r )) 0 0
  #     addstr "The Drench" 1 20
  #     sleep 0.001
  #   done
  # done
  # getkey
  x=0 label=$(minimenu SSH Automations Info)
  x=14 label=$(minimenu AAU1-FE AAU2-FE AAU3-FE AAU4-G45)
  x=28 label=$(minimenu VM01 VM02 VM03 VM04 VM05)
  restore
  bash
}

trap restore EXIT
setup
main
